export const getAll = () => Promise.resolve('from getAll')
export const getOne = () => Promise.resolve('from getOne')
export const create = () => Promise.resolve('from create')
export const update = () => Promise.resolve('from update')
export const remove = () => Promise.resolve('from remove')
export const search = () => Promise.resolve('from search')
